### ISSUE TITLE
Fix bash scripts to conform to ShellCheck rules

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovatebot.github.io#109]
**What browser are you using?**

Not relevant to report.

**Describe the bug**

Shell Check program/website reports problems with our `.sh` scripts.

**Steps to reproduce**

1. Go to https://github.com/renovatebot/renovatebot.github.io/tree/main/bin
1. Copy/paste the shell script code into the ShellCheck website. [^website]
1. See problems for at least the `bin/get-docs.sh` file.

**Additional context**

We should follow the best practices from the ShellCheck website.

[^website]: https://www.shellcheck.net/

**Comment by viceice** [comment]
Is there a way to integrate as ci check?

**Comment by HonkingGoose** [comment]
> Is there a way to integrate as ci check?

Yes! 😉 

Read https://github.com/koalaman/shellcheck#in-your-build-or-test-suites to learn more.

**Comment by viceice** [comment]
💪 can you open a PR? I'll fix the issues then.

**Comment by HonkingGoose** [comment]
The default Ubuntu 20.04 GitHub Actions environment already has the shellcheck program installed, according to the docs. [^docs]

<html><body>


shellcheck | 0.7.0-2build2
-- | --



</body>
</html>

[^docs]: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#installed-apt-packages
