### ISSUE TITLE
Move `src/index.md` page to main Renovate repository?

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovatebot.github.io#119]
**What would you like to be able to do?**

It's a bit confusing that the homepage/index is in the `renovatebot.github.io` repo.

This has a few drawbacks:

- You cannot suggest changes to the homepage via the "pencil" button on the published docs homepage (because the file is not in the main renovatebot repo)
- It splits the documentation into two parts
- It also means that the "publish docs as assets" is missing a suitable index/homepage/startpoint as well

I think our overall goal is to move all the docs back to the main renovate repository, build the docs over there, and import the docs/asset files into the docs-building repo?

**Did you already have any implementation ideas?**

Maybe we can move the `src/index.md` file to a suitable place in the main Renovate bot repository, and then make it so that `mkdocs` understands where to find/insert the homepage in the docs building step in our makefile?

I'm talking about this file: https://github.com/renovatebot/renovatebot.github.io/blob/main/src/index.md

**Comment by rarkins** [comment]
https://docs.renovatebot.com/ is not meant for *exclusively* content from github.com/renovatebot/renovate. It's therefore not for sure that we should move such information into that repo in case it needs to start referring to other repos

**Comment by HonkingGoose** [comment]
Oh okay, let's leave things as they are now then. 😄
