### ISSUE TITLE
Improve Renovate update config for `mkdocs-material`

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovatebot.github.io#121]
**What would you like to be able to do?**

Right now I have to manually request updates to `mkdocs-material`, for `minor` bumps from the maintainers of this repository.

I don't know what the original reasoning was to require dashboard approval for `minor` Python package updates?

I would much rather have Renovate open update PRs for `mkdocs-material` automatically, and then wait for our approval. This would reduce the need for me to bother you to update. 😄 

**Did you already have any implementation ideas?**

We get our Renovate config from two places:

- Global config: https://github.com/renovatebot/.github/blob/main/default.json
- Local config: https://github.com/renovatebot/renovatebot.github.io/blob/main/renovate.json

I think we can make a custom `packageRule` for just `mkdocs-material` and put it at the bottom of the `packageRules` array?

I was thinking of defining the rules for `mkdocs-material` like this:

- Keep `stabilityDays` at `3`
- Always open a PR for all update types automatically, even for `major` updates
- Always require PR approval
- Optional: automerge `patch` level updates "behind our back" via branch automerge, like we do now already

Let me know what you think of this idea, and what rules you would like to have?

**Comment by viceice** [comment]
Sounds good, suggest a PR in this repo to override settings

**Comment by viceice** [comment]
Intention was to not silently break our docs.

**Comment by viceice** [comment]
So remove approval and disable automerge for minor. 🤗
