### ISSUE TITLE
Use reviewdog/action-shellcheck

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovatebot.github.io#133]
**What would you like to be able to do?**

We should use the [reviewdog/action-shellcheck](https://github.com/reviewdog/action-shellcheck) github action for shell check to have nice annotations

**Did you already have any implementation ideas?**

**Comment by viceice** [comment]
- https://github.com/containerbase/buildpack/pull/264

**Comment by RahulGautamSingh** [comment]
@viceice Can you assign me to this, I have already added the solution for #135 's branch will create a new PR for this one.
