### ISSUE TITLE
Setup and use `lint-staged` in development and in CI runs

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovatebot.github.io#135]
**What would you like to be able to do?**

@viceice wanted me to install/configure `lint-staged`, but I don't know how I should set it up. 🙈 

**Did you already have any implementation ideas?**

Let @viceice do it. 😉

**Comment by RahulGautamSingh** [comment]
@viceice @HonkingGoose Is it okay if I work on this one? If there is anything similar in Renovate, I can look over it; otherwise, I can learn it.

**Comment by viceice** [comment]
Sure, there should be some repos using this, eg the `containerbsse/buildpack` repo.
