### ISSUE TITLE
Add `security-and-permissions.md` to sidebar

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovatebot.github.io#141]
**What would you like to be able to do?**

Add `security-and-permissions.md` file to the sidebar.

Follow up for https://github.com/renovatebot/renovate/pull/13748.

**Did you already have any implementation ideas?**

When we see the file on our `main` branch we can add it in the sidebar and check the preview locally.

**Comment by rarkins** [comment]
File maybe needs some preamble first to make it clear what it's about?
