### ISSUE TITLE
Merge confidence image hosted on GitHub not rendering in published docs

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovatebot.github.io#167]
### What browser are you using?

Firefox

### Describe the bug

I added a screenshot to the [`readme.md` file for the "Merge Confidence"](https://github.com/whitesource/merge-confidence/blob/main/README.md) docs. You can see the screenshot when you view the `readme.md` on GitHub, but you can't see the screenshot on the [published page](https://docs.renovatebot.com/merge-confidence/).

The alt text "Renovate PR with Merge Confidence badges" is visible on the published page though, and it's in an `<img>` element, the `src=` property points to the correct place as well. So at least _something_ is rendering... 🙈 

### Steps to reproduce

1. View the [`readme.md` source file on GitHub](https://github.com/whitesource/merge-confidence/blob/main/README.md) -> image present.
1. Now view the published page [Renovate docs, Merge Confidence](https://docs.renovatebot.com/merge-confidence/) -> image missing.

### Additional context

View the [Renovate docs, pinning dependencies and lock files](https://docs.renovatebot.com/dependency-pinning/#pinning-dependencies-and-lock-files), the images are working properly there.

The images that work are in the [main Renovate repo under `docs/usage/assets/images`](https://github.com/renovatebot/renovate/tree/main/docs/usage/assets/images).

I'm not sure _why_ it works when images are under `docs/usage/assets/images` and it breaks when I link to an external image on GitHub.

**Comment by rarkins** [comment]
Is the image URL it points to correct? And if so then it's a matter of that the image is missing?

**Comment by viceice** [comment]
![image](https://user-images.githubusercontent.com/1798109/165451576-aa711aa1-8321-4cb1-911d-22d5b7a343cc.png)
url is pointing to repo and returns wrong 

This PR should fix the url
- https://github.com/whitesource/merge-confidence/pull/1642

**Comment by viceice** [comment]
![image](https://user-images.githubusercontent.com/1798109/165467038-9ae9a59b-5b09-4375-8211-02250f918e14.png)
works 🎉

**Comment by HonkingGoose** [comment]
Thank you @viceice for fixing the link!

I didn't know that CORB was blocking the image from displaying. So next time I want to link to images on GitHub, I should use `https://raw.githubusercontent.com/` as the domain. 😄
