### ISSUE TITLE
Renovate bot automerges PRs for git submodule `renovatebot/renovate` with failing build

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovatebot.github.io#179]
### Describe the proposed change(s).

Renovate bot automerges PRs which have a failing test, for example:

- https://github.com/renovatebot/renovatebot.github.io/pull/178

We should update out branch protection rules for the `main` branch, so that it checks if the build passes.

**Comment by HonkingGoose** [comment]
@rarkins or @viceice Did you update the branch protection rules for the `main` branch?

**Comment by viceice** [comment]
yes
