### ISSUE TITLE
Add custom `edit_url` for the Merge Confidence page

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovatebot.github.io#188]
### What would you like to be able to do?

The pencil/edit button on the [Merge Confidence page in our docs](https://docs.renovatebot.com/merge-confidence/) doesn't point to the correct location.

The documentation build pulls in the `README.md` file from [`whitesource/merge-confidence`](https://github.com/whitesource/merge-confidence). This means our default "edit button link" doesn't work for this page. We can fix this by using the new `edit_url` hook.

### Did you already have any implementation ideas?

Put this front matter in the code that we use to load in the `README.md` from the `whitesource/merge-confidence` repository:

```markdown
---
edit_url: https://github.com/whitesource/merge-confidence/edit/main/README.md
---
```

We should probably update these lines of code:

https://github.com/renovatebot/renovatebot.github.io/blob/a6b1afca75d89eeb4846d8b461575685abc31f44/bin/get-docs.sh#L25-L26

### Do you want to write this feature yourself?

No

**Comment by viceice** [comment]
I'm not sure if we should add it to source file or simply prepend it after download?

@rarkins WDYT?
