### ISSUE TITLE
Replace `yarn build:docs` with proper command in `get-docs.sh` script

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovatebot.github.io#208]
### Describe the proposed change(s).

https://github.com/renovatebot/renovatebot.github.io/blob/38aae6745b14dfcb7399a27d8c456a579ead8012/bin/get-docs.sh#L15-L18

The `yarn build:docs` command listed above doesn't work.

We have three scripts in our `package.json` now:

https://github.com/renovatebot/renovatebot.github.io/blob/38aae6745b14dfcb7399a27d8c456a579ead8012/package.json#L14-L18

We should update our `get-docs.sh` script so it works again. 😉

**Comment by viceice** [comment]
Nope, you missed this `cd` , so we are in `deps/renovate` when calling yarn 😉 

https://github.com/renovatebot/renovatebot.github.io/blob/38aae6745b14dfcb7399a27d8c456a579ead8012/bin/get-docs.sh#L13
