### ISSUE TITLE
Supported Datasources documentation missing

### ISSUE THREAD

**Issue by ChipWolf** [renovatebot/renovatebot.github.io#23]
In the Renovate Docs under _Renovate Modules_ > _Datasources_. The expected content under the _Supported Datasources_ heading is missing.

https://docs.renovatebot.com/modules/datasource/#supported-datasources

https://github.com/renovatebot/renovate/blob/master/docs/usage/modules/datasource.md

**Comment by viceice** [comment]
duplicator of #21
