### ISSUE TITLE
Support for other languages

### ISSUE THREAD

**Issue by JamieMagee** [renovatebot/renovatebot.github.io#231]
### What would you like to be able to do?

In light of the translation effort happening in Renovate (https://github.com/renovatebot/renovate/pull/17768) I thought it might be reasonable to also provide support for translating documentation.

### Did you already have any implementation ideas?

`mkdocs-material` has a page[^1] dedicated to changing the language and already has support for a language picker built-in.

[^1]: https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/

### Do you want to write this feature yourself?

No

**Comment by HonkingGoose** [comment]
The linked PR (https://github.com/renovatebot/renovate/pull/17768) was closed. I don't see any more work on a Renovate translation. Translating the docs and/or Renovate code is a massive undertaking, which needs maintainer level support and contributors who are native speakers for the the target language.

I guess we should close this issue?

**Comment by rarkins** [comment]
Yes, we have no way to support the effort required directly so this would require a community contribution. Happy to reopen if someone wants to volunteer
