### ISSUE TITLE
Migrate from pipenv to poetry

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovatebot.github.io#245]
### Describe the proposed change(s).

pipenv only supports contraining a single python version, but i like to express `>=3.9`.
pipenv also seems to have difficulties when running with a lower python version (like 3.8 on gitpod) when the lockfile was generated with a higher python (due to renovate)

- https://github.com/yhino/pipenv-poetry-migrate

**Comment by HonkingGoose** [comment]
Sounds good to me. We should have a setup that works on Gitpod/Codespaces and locally. That way contributors can use what works best for them.
