### ISSUE TITLE
anchor links dont work in desktop safari

### ISSUE THREAD

**Issue by iamstarkov** [renovatebot/renovatebot.github.io#268]
### What browser are you using?

Safari on macOS

### Describe the bug

when you open or click on https://docs.renovatebot.com/configuration-options/#updateinternaldeps in desktop safari page opens but doesn't scroll to the "update internal deps" heading/title like it does in chrome
![Screenshot 2023-01-31 at 13 20 22](https://user-images.githubusercontent.com/559321/215758139-9bb15b36-925f-4fc8-b66a-3fd9ec44e9e8.png)

### Steps to reproduce

1. Open https://docs.renovatebot.com/configuration-options/#updateinternaldeps
2. Observe that scroll posisiton is on top of the page, and not being scrolled to the relevant header

### Additional context

Console is empty of errors in Safari and anchor links not working not limited to just this one anchor link, im sure none of the left sidebar anchor links work

**Comment by HonkingGoose** [comment]
Thank you for reporting the problem. ❤️

It sounds like this upstream issue is related:

- https://github.com/squidfunk/mkdocs-material/issues/3797

The Material for MkDocs maintainer has this to say about the upstream issue: [^quote]

> So, a heads up: I'm aware of this issue, but solving it turns out to be very complex. I'm going to take this as an opportunity to refactor instant loading, which definitely needs to be simplified, also solving the issue at hand. However, I need to find enough time to do this, so I currently can't put an estimate on when this will be fixed.
> 
> In the meantime, disabling instant loading is a good workaround.

Here's the relevant config in our repository:

https://github.com/renovatebot/renovatebot.github.io/blob/c62a89540e25464ead8d29cd2553952d0b741bb3/mkdocs.yml#L90-L92

Instant loading is the killer feature of Material for MkDocs, and it does speed up clicking around in the docs a lot. So I don't really want to disable instant loading. I'll let the maintainers weigh the pros and cons, and let them decide. 😄 

[^quote]: https://github.com/squidfunk/mkdocs-material/issues/3797#issuecomment-1107816067

**Comment by viceice** [comment]
i see wrong scrolling from search regularly on Android mobile chrome. it's gotten better with latest release.

**Comment by HonkingGoose** [comment]
Hi @iamstarkov! 👋 

Can you try to reproduce the problem again? Material for MkDocs has gotten some fixes, so maybe the bug is fixed now.

If the new patches didn't fix the bug, then I'd like to test things by:

1. Disabling the `navigation.instant` feature for a short while
1. Let the bug reporter test Safari on macOS again
1. Based on the feedback: decide if we want to disable the instant loading, or keep it and accept that Safari on macOS is a bit broken

**Comment by HonkingGoose** [comment]
Looks like version `9.1.1` of Material for MkDocs [^release-notes] fixes this:

> - Fixed https://github.com/squidfunk/mkdocs-material/issues/5023: Instant loading not allowing to go back to initial page
> - Fixed https://github.com/squidfunk/mkdocs-material/issues/3797: Instant loading does not work with section anchors in Safari

All we have to do now is wait until we reach the `stabilityDays` threshold for Renovate to automatically update us. Or a maintainer can manually approve the update earlier (if they want).

[^release-notes]: https://github.com/squidfunk/mkdocs-material/releases/tag/9.1.1

**Comment by HonkingGoose** [comment]
@viceice Our production deployment is still using the _broken_ version. The fixed version is awaiting the `stabilityDays` before it auto-merges, but you can speed things up manually, if you want.

**Comment by iamstarkov** [comment]
@viceice it works now indeed!
