### ISSUE TITLE
Github mixed with Gitlab - Typo?

### ISSUE THREAD

**Issue by arxeiss** [renovatebot/renovatebot.github.io#27]
This is the page about **Gitlab app Installation** https://docs.renovatebot.com/install-gitlab-app/#configuring-a-token-for-githubcom-hosted-release-notes, but there is header of section talking about GitHub.

Is that just a typo, or wrong placed part of the documentation?

**Comment by rarkins** [comment]
It's 100% correct as is

**Comment by rarkins** [comment]
Read beyond the header!

**Comment by arxeiss** [comment]
I'm sorry. I read the whole section before, but I understood it badly. After second read it makes sense... 
My fault, thank you for the quick reply

**Comment by rarkins** [comment]
It could definitely be explained more clearly though, the original source content is in the main repo if you're interested
