### ISSUE TITLE
Use Docusaurus

### ISSUE THREAD

**Issue by ctison** [renovatebot/renovatebot.github.io#28]
Hello,

I read Renovate's documentation through Docusaurus and I finally understood the configurations 😅. (Or maybe was it because it was the second time I read it 🥱).

https://github.com/ctison/renovate-doc -> https://renovate-doc.vercel.app

Using Docusaurus v2 would also allow to easily integrate Algolia (free plan for open source) (cf. https://v2.docusaurus.io/docs/search).

Are you interested I fix things and open a PR ?

**Comment by viceice** [comment]
see renovatebot/renovate#6944 for planned docs changes

**Comment by rarkins** [comment]
@ctison hoping you can jump into the other conversation!

**Comment by viceice** [comment]
@ctison Can we resuse code from your repo https://github.com/ctison/renovate-doc? As we are planning to use docusaurus v2

**Comment by ctison** [comment]
Yes of course, permission is hereby granted to reuse the code without notification bla bla bla.
