### ISSUE TITLE
Hint for GitHub app installation access token retrieval

### ISSUE THREAD

**Issue by MShekow** [renovatebot/renovatebot.github.io#288]
### What would you like to be able to do?

In the docs https://docs.renovatebot.com/modules/platform/github/#running-as-a-github-app there is the following section:

```
token:"ghs_123exampletoken"

You must use a [GitHub App Installation token](https://docs.github.com/en/developers/apps/building-github-apps/authenticating-with-github-apps#authenticating-as-an-installation).
```
It would be nice to add a few helpful links for how to retrieve this GitHub App installation (access) token.

### Did you already have any implementation ideas?

- If you run Renovate via a regularly scheduled GitHub Actions workflow, you can use the actions https://github.com/jnwng/github-app-installation-token-action or https://github.com/tibdex/github-app-token
- If you use some other CI/CD system (e.g. Azure DevOps) which supports running _container_-based jobs, you can use https://github.com/MShekow/github-app-installation-token

If you think this is a worthwhile addition to the docs, I could create a PR.

### Do you want to write this feature yourself?

Yes

**Comment by rarkins** [comment]
Hi, the source for that page is in https://github.com/renovatebot/renovate/blob/main/lib/modules/platform/github/index.md, so please submit a PR there
