### ISSUE TITLE
Add automerge configuration guide to sidebar

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovatebot.github.io#30]
@viceice mentioned we need to make some changes in this repository to get the new automerge configuration guide (https://github.com/renovatebot/renovate/pull/7724) in the sidebar of the Renovate documentation site?

I can find the new docs with the search function, but I don't see it in the sidebar when I fully expand all items in the sidebar.
Am I maybe missing it?

Link to public docs: https://docs.renovatebot.com/automerge-configuration/

To reproduce:

1. Go to Renovate Docs homepage.
1. Expand all sidebar items.
1. Search for `automerge` in your browser, get 0 hits.

**Comment by viceice** [comment]
needs to be added somewhere below here:

https://github.com/renovatebot/renovatebot.github.io/blob/39532b83fd02b1e9aea068ea9af7f384e5f216b5/mkdocs.yml#L26
