### ISSUE TITLE
Switch to `pnpm` on this repository

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovatebot.github.io#308]
### Describe the proposed change(s).

We recently switched the main `renovatebot/renovate` repository from `yarn` to `pnpm`. Do you guys want to switch to `pnpm` here as well?

**Comment by viceice** [comment]
sure, if we use yarn v1 here

**Comment by viceice** [comment]
We should switch to pnpm for better caching

**Comment by HonkingGoose** [comment]
Closed by PR:

- #346
