### ISSUE TITLE
Publishing new docs fails but we use updated `.pages` from upstream submodule

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovatebot.github.io#344]
### What browser are you using?

Firefox

### Describe the bug

Our docs site is not updating properly. I recently moved the Bot comparison page to the All Other section of the sidebar. The Renovate submodule in current `main` has the _new_ `.pages` file where the Bot Comparison page is moved.

The Cypress test is failing on the `main` branch, I think this is blocking GitHub Pages from using the new stuff?

- [Upstream PR that moved Bot comparison page](https://github.com/renovatebot/renovate/pull/25547)
- [Failed Cypress test on `main`](https://github.com/renovatebot/renovatebot.github.io/actions/runs/6766495609/job/18387690492)

### Steps to reproduce

1. Go to [this repository's commit overview](https://github.com/renovatebot/renovatebot.github.io/commits/main/).
2. Select test result for the latest commit (`10c48bc`).
3. Read test failure.
4. Go to Renovate docs site, see Bot comparison page is still the second page!

### Additional context

Our Cypress test for the next/previous buttons used to rely on having a certain page be the "Next Page"... I wonder if we're running into a similar problem now?

**Comment by rarkins** [comment]
I thought that the idea of moving the page was to get the Cypress test passing again?

**Comment by HonkingGoose** [comment]
Yeah, I thought that moving the page would fix the Cypress test. But it didn't. 🙃 Looks like we will need to dig deeper to find out what's going wrong.

**Comment by viceice** [comment]
will hopefully fixed by cypress 13.4.0[^1], trying to enforce the update now

[^1]: https://docs.cypress.io/guides/references/changelog#13-4-0
