### ISSUE TITLE
Automatically upgrade Python version in Vercel environment script

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovatebot.github.io#389]
### What would you like to be able to do?

We have a `PYTHON_VERSION=3.12.1` constant in our Vercel build script, which we should keep current. Right now, we can only update this constant by hand. We should find a way to automate updating this version.

Here's the link to the [`bin/prepare-vercel.sh` script](https://github.com/renovatebot/renovatebot.github.io/blob/main/bin/prepare-vercel.sh).

### Did you already have any implementation ideas?

Configure Renovate to update the version for us.

### Do you want to write this feature yourself?

No

**Comment by viceice** [comment]
this is blocked until I automatically publish newer versions to containerbase python-prebuild. currently I build them manually, so no way to automatically update it here.

**Comment by HonkingGoose** [comment]
I'll assign this issue to you then `@viceice`, so you can fix this when ready. 😉
