### ISSUE TITLE
setup Prettier + create GitHub Action that lints with Prettier?

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovatebot.github.io#42]
Do we want to setup a Prettier configuration + CI that checks for Prettier errors on this repo?
I use Prettier to good effect on my simple Docusaurus v2 repo, but it might get complicated due to some autogenerating content.

Somebody who knows how the build process works should set up the `prettierignore` file so that we're only prettifying things we care about.

**Comment by viceice** [comment]
Sure, let's do this when we switch to docusaurus. I'll try to make progress on next week's

**Comment by viceice** [comment]
Lets add `husky` and `lint-staged` for `pre-commit` validation
