### ISSUE TITLE
Create issue templates

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovatebot.github.io#43]
I was thinking about making a PR to create issue templates for bugs and feature requests.
But then I realized that I don't know what those issue templates should cover.... 😄 

I think in the end, once we've migrated to Docusaurus, the main things we would probably handle on this repository are:
- Styling bugs
- Usability concerns
- Broken stuff due to the migration process
- Missing stuff due to the migration process
- Maybe security bugs related to Docusaurus (those should go upstream to Docusaurus themselves probably).

Maybe we should wait a bit until we are clear on what this repo is going to contain before creating issue templates?

**Comment by viceice** [comment]
Sounds good
