### ISSUE TITLE
Maybe update the issue discussion lock bot?

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovatebot.github.io#44]
I noticed we have a bot that locks further discussion on closed issues after 7 days: https://github.com/renovatebot/renovatebot.github.io/blob/build/.github/lock.yml

Maybe you should use the GitHub Actions based bot instead of the current bot?

From https://github.com/dessant/lock-threads-app/blob/master/README.md:
> This project is in maintenance mode, migrating to the version built on GitHub Actions is recommended: https://github.com/dessant/lock-threads

**Comment by viceice** [comment]
Sure, can you migrate it from main renovate repo?

**Comment by viceice** [comment]
@rarkins can you remove the lock bot app from org. I think it won't work anyways.

**Comment by rarkins** [comment]
It's removed
