### ISSUE TITLE
No Git submodule updates for `renovatebot/renovate`

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovatebot.github.io#490]
### Describe the proposed change(s).

Renovate used to update the Git submodule for the main `renovatebot/renovate` repository regularly.

It has been five days since the last `chore(deps): update deps/renovate digest to ....`-type update on the docs repo's `main` branch.

I don't know _why_ Renovate stopped giving us the Git submodule updates. We recently made a lot of changes to the docs structure and files, maybe those changes broke something? I'm not seeing any obviously failing tests on the `renovate/deps-renovate-digest` branch. There may be information in the logs though.

I'll let a maintainer figure out what's causing this, and fix the problem. :wink:

**Comment by viceice** [comment]
It's working again. was due to broken / failing devcontainer workflow
