### ISSUE TITLE
Require branches to be up to date before merging?

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovatebot.github.io#50]
The main Renovate bot repo has The **Require branches to be up to date before merging** checkbox ticked on the Branch Protection tab in the repo settings.

It might be a good idea to enforce the integration of the mainline branch into the PR branch on this repository as well.

**Comment by HonkingGoose** [comment]
Hmm, I don't know if this will work right-now, we don't have any **required tests** yet?

I've checked in one of my repo branch protection settings what the requirements are to tick the box:

> **Require branches to be up to date before merging**
This ensures pull requests targeting a matching branch have been tested with the latest code. This setting will not take effect unless at least one status check is enabled (see below).

**Comment by rarkins** [comment]
Doing so does slow things down quite a bit - is it worth it here? we do so in a code-heavy repo in case two PRs influence each other but less likely here right now.

**Comment by HonkingGoose** [comment]
I agree, waiting around for the tests to run is not very nice.
I like to be sure that my work is not messing up the mainline because my PR branch was behind on some critical change, so that's why I like to enforce that PR commits are tested with the latest mainline branch.

But we don't (yet) have any meaningful tests, and we're not fully migrated to Docusaurus v2 yet, so we are probably safe holding out on this feature until we find we need it.
