### ISSUE TITLE
Sidebar item visiblity

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovatebot.github.io#60]
**What would you like to be able to do?**

We're currently hiding items in the sidebar by default.
This can cause users to miss useful information like the "Versioning" help in the `docs/usage/modules/versioning.md` file.
So maybe we want to just show all items and not hide anything for now.

Once we migrate to Docusaurus v2 we have a lot more control over what items we want to be visible in the sidebar and which we want to hide: https://v2.docusaurus.io/docs/sidebar#expanded-categories-by-default

**Did you already have any implementation ideas?**

I have checked the MkDocs documentation, and I don't know if the current theme we're using supports the `navigation_depth` property or not. 

> `navigation_depth`: The maximum depth of the navigation tree in the sidebar. Default: `2`.

I was thinking we could increase the maximum depth of the tree to get more items to be visible on the sidebar.
See https://www.mkdocs.org/user-guide/styling-your-docs/#mkdocs and search on the page for `navigation_depth` to find the docs for this property.

We can also wait with this change until we've migrated to Docusaurus v2.

**Comment by HonkingGoose** [comment]
The "show full sidebar idea" was discussed on the main renovatebot repository here: https://github.com/renovatebot/renovate/pull/9017 prior to me opening this issue.

**Comment by rarkins** [comment]
Yeah, I recall I didn't like the look of it either because there wasn't granular control
