### ISSUE TITLE
Add dashboard page to getting started section

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovatebot.github.io#68]
**What would you like to be able to do?**

See https://github.com/renovatebot/renovate/issues/11178 and https://github.com/renovatebot/renovate/pull/11183

**Did you already have any implementation ideas?**

**Comment by HonkingGoose** [comment]
We changed plans, the file is now in this path over on the Renovate main repo: `/docs/usage/key-concepts/dashboard.md`.

**Comment by viceice** [comment]
Ups, nav needs Update anyways. 🤗

**Comment by HonkingGoose** [comment]
The new `key-concepts` category and the new `dashboard.md` file need to be placed on the sidebar in their correct places. 😉

**Comment by HonkingGoose** [comment]
This issue can be closed as commit https://github.com/renovatebot/renovatebot.github.io/commit/e9a9598f38ff8c95502261b99c4fc60c526281f1 adds the new key concepts menu to the sidebar, and also adds the dependency dashboard page. 😄
