### ISSUE TITLE
Index page: Link to npm.js results in 404 not found for `renovate` package

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovatebot.github.io#69]
**What browser are you using?**

Firefox.

**Describe the bug**

Link to our `renovate` package on NPM results in a 404 not found from npm.js

**Steps to reproduce**

1. Go to https://docs.renovatebot.com/
2. Click on link with text `an Open Source npm package`
3. See npm.js not found, with picture of a wombat.

**Additional context**

Source file for the index page is: https://github.com/renovatebot/renovatebot.github.io/blob/build/src/index.md

**Comment by HonkingGoose** [comment]
@rarkins I like the new index page! Just a little bug sneaked it's way in. 😉

**Comment by rarkins** [comment]
Fixed, thanks
